# frozen_string_literal: true

module Commands
  PING_COMMAND = 'PING'
  ECHO_COMMAND = 'ECHO'
  SET_COMMAND = 'SET'
  GET_COMMAND = 'GET'
  DEL_COMMAND = 'DEL'
  INFO_COMMAND = 'INFO'
  REPLCONF_COMMAND = 'REPLCONF'
  PSYNC_COMMAND = 'PSYNC'
end
